project:
  type: website

website:
  title: "![James Le Houx - Research Logo](/assets/logo.png){height=50px} JAMES LE HOUX"
  site-url: https://jameslehoux.com
  description: "Researcher and Emerging Leader in battery characterisation, synchrotron science, and computational modeling."
  favicon: /assets/logo.svg
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    tools:
    - icon: github
      href: https://github.com/jameslehoux
    - theme-toggle: true
    right:
      - text: About
        href: about/index.qmd
      - text: Publications
        href: publication/index.qmd
  
  page-footer:   
    left: >-
      © 2025 James Le Houx · Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://bsky.app/profile/thebeamline.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a> 
      <a class="link-dark me-1" href="https://linkedin.com/in/jameslehoux/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a> 
      <a class="link-dark me-1" href="https://github.com/jameslehoux" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a> 
      <a class="link-dark me-1" href="https://orcid.org/0000-002-1576-0673" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=m4oegGQAAAAJ&hl=en" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
    right: 
      - text: "Accessibility"
        href: accessibility.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "License"
        href: license.qmd
      - text: "· Design inspired by Silvia Canelón"

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/james-theme-light.scss
      dark: 
        - cosmo
        - assets/james-theme-dark.scss
    highlight-style:
      light: assets/james/a11y-light.theme
      dark: assets/james/a11y-dark.theme
    code-link: false
    include-in-header:
    -   text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;700&family=Raleway:wght@200;400;500;700&display=swap" rel="stylesheet">
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute: 
  freeze: auto
