---
comments: false
date: "2025-08-20T12:30:00+01:00"
title: "Accessibility Commitment"
---

Return to the [home page](/index.qmd), explore my [publications](publication/index.qmd), or learn more [about me](about/index.qmd).

## Feedback

I am committed to making my website and research materials accessible to everyone. I welcome your feedback on the accessibility of this site—please let me know if you encounter any barriers by using my [contact page](/contact.qmd). I will do my best to respond promptly and address the issue.

Thank you for visiting and for taking the time to read this page.

---

## Accessibility Practices

This website is built with the following accessibility features in mind:

-   **Color Contrast**: A color scheme designed to meet the Web Content Accessibility Guidelines (WCAG) 2.1 AA standards for contrast.
-   **Alternative Text**: Alternative text (alt text) for all informative images and figures to ensure they are understandable to users of screen readers.
-   **Typography**: Clear, readable fonts and a logical heading structure to aid navigation and comprehension, particularly for users with visual impairments or reading disabilities.
-   **Navigation**: A simple and consistent navigation structure across the site.
-   **Compatibility**: Use of semantic HTML to ensure compatibility with a wide range of browsers and assistive technologies.

---

## Continuous Improvement

As a research scientist, not a professional web developer, I am continuously learning how to implement better accessibility practices in the content I create.

My plan is to regularly audit this site for accessibility issues and learn how to remedy them as best I can. I will be using standard evaluation tools to guide this process:

-   [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/)

I will document significant accessibility issues and any corrective actions in the [public GitHub repository for this site](https://github.com/jameslehoux/website).